Portfolio profile
edubew/winnie-s_portfolio pull request #1
Opened 2022-02-17 01:52 UTC by edubew

## In this milestone  I was able to:
- Create a new branch portfolio-profile
- Create an index.html file with a navigation bar and header area for the project
- Create a style.css file and added styling to the header and navigation bar 
- Check for linters errors
- Fix linters errors in both index.html and style.css files

2022-02-17 03:13 UTC, micheaol requested changes
Hi @edubew , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## TO HIGHLIGHT: 
- Your project is professional 💯 
- Your repo is professional 💯 
- Well structured files 💯 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-17 03:13 UTC, micheaol commented on index.html
> +            <img src="IMG1/icon.png" alt="Bars">
Please ensure that the hamburger button has a `nav` tag.

`<header>`
         `nav`
            `<img src="IMG1/icon.png" alt="Bars">`
        `nav`
`</header>`

2022-02-17 03:13 UTC, micheaol commented on index.html
> +    <header>
Please ensure that the container of the section is a `section` tag

2022-02-17 03:13 UTC, micheaol commented on index.html
> +    </header>
Please ensure that you stick to the design as much as possible (e.g. font, colors, images, tests, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). Styling: Active, Hover and Pressed for ALL buttons.

Your Implementation | Figma Design
:---:|:---:
![image](https://user-images.githubusercontent.com/10332499/154397234-8b9104d9-4dfc-4cd3-a848-854715902c71.png) | ![image](https://user-images.githubusercontent.com/10332499/154397426-e4cdde22-0e0c-409b-aa84-1867f606b81b.png)

2022-02-18 09:27 UTC, AnselemOdims approved these changes
### Hi  @edubew 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions
- [ ] I would suggest you prevent the horizontal scroll on the page as this not a good user experience
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-18 09:31 UTC, edubew commented
Hello @AnselemOdims 
How do I prevent a horizontal scroll on the page?

2022-02-18 10:06 UTC, merged