Deployed with Github pages
edubew/winnie-s_portfolio pull request #9
Opened 2022-02-28 20:15 UTC by edubew

## In this milestone:
- I have Deployed my portfolio with Github pages

2022-02-28 20:43 UTC, Deepakdanger requested changes
Hi @edubew, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-28 20:43 UTC, Deepakdanger commented on README.md
> +[Winnie's Portfolio](https://edubew.github.io/winnie-s/portfolio/)
- [ ] The provided link is broken or not working, Kindly add the correct `deployed website link` in the `Readme` file.

2022-02-28 21:05 UTC, edubew commented
Hello,
I am following all the steps provided in the documentation but my link
still won't work. I don't know how else to fix it


On Mon, Feb 28, 2022, 23:43 Deepak ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @edubew <https://github.com/edubew>,
>
> Good job so far! 👏
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> You can also consider:
>
>    - N/A
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In README.md
> <https://github.com/edubew/winnie-s_portfolio/pull/9#discussion_r816235768>
> :
>
> > @@ -10,14 +10,35 @@
>
>  - CSS
>
>  - LINTERS
>
>
>
> +## Live Demo
>
> +[Winnie's Portfolio](https://edubew.github.io/winnie-s/portfolio/)
>
>
>
>    - The provided link is broken or not working, Kindly add the correct deployed
>    website link in the Readme file.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/edubew/winnie-s_portfolio/pull/9#pullrequestreview-895573571>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS5ANASKZ7QU4C3NIYIFXXTU5UVXHANCNFSM5PSCHUVA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-01 07:26 UTC, jenadiusnicholaus reviewed
Hi @edubew 

Good job !
[Optional]

I think you are missing `Live link` part in you ReadMe file

2022-03-01 09:03 UTC, AnselemOdims approved these changes
### Hi  @edubew 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-01 09:41 UTC, merged